### ISSUE TITLE
KeyVault name should be a parameter

### ISSUE THREAD

**Issue by jadarsie** [deaborch/aks-engine-guard-integration#6]
The same with `authorization-webhook-cache-authorized-ttl` and `authentication-token-webhook-cache-ttl`.

Is not this dependent on K8s version?

I do not think that this line should assume that these properties are always missing

https://github.com/deaborch/aks-engine-guard-integration/blob/main/images/daemonset/script.sh#L61

**Comment by deaborch** [comment]
Fixed
